const location1 = [
  "Ammunition Store",
  "Auto Fair №1",
  "Auto Fair №2",
  "Autosalon",
  "Bahama Mamas Bar",
  "Capitol",
  "Casino",
  "Cayo Perico Island",
  "Chumash",
  "Church",
  "Del Perro",
  "Diamond Resort Bar (Casino Restaurant)",
  "Downtown Vinewood",
  "Eclipse Tower",
  "El Burro Heights",
  "Fire Station",
  "Hospital",
  "Lifeinvader",
  "Little Seoul",
  "Mirror Park",
  "Paleto Bay",
  "Postal",
  "Residential Complex",
  "Richman",
  "Rockford Hills",
  "Sandy Shores",
  "Stadium",
  "Stock Exchange",
  "Tequi-la-la Bar",
  "Tinsel Tower",
  "Vanilla Unicorn Bar",
  "Vespucci Canals",
  "Vinewood Hills",
];

const location2 = [
  "airport",
  "beach",
  "beach market",
  "fire station",
  "ghetto",
  "post office",
  "the city",
  "train station",
];

const autoNames = [
  "9F Cabrio",
  "9F",
  "Adder",
  "Albany Escalade",
  "Alpha",
  "Alpha-Z1",
  "Annis 350Z",
  "Annis GT-R I",
  "Annis RX-7 (FD)",
  "Annis Silvia (S15)",
  "Annis Skyline GT-R (R34)",
  "Annis WRX 2004",
  "Annis ZR-350",
  "Apocalypse Impaler",
  "Apocalypse Imperator",
  "Apocalypse Issi",
  "Apocalypse Slamvan",
  "Ardent",
  "Asbo",
  "Asea",
  "Asterope",
  "Autarch",
  "Baller LE LWB",
  "Baller SG",
  "Baller",
  "Banshee 900R",
  "Banshee",
  "Beater Emperor",
  "Beater Mariachi Tornado",
  "Beater Surfer",
  "Beater Tornado",
  "Benefactor-AMG C63 (W205)",
  "Benefactor-AMG C63 Coupe (W205)",
  "Benefactor-AMG G63 (G770)",
  "Benefactor-AMG GT 63 (S)",
  "Benefactor-AMG GT Black Series",
  "Benefactor-AMG S63 (W222)",
  "Benefactor-Benz 600SEL (W140)",
  "Benefactor-Benz E420 (W210)",
  "Benefactor-Benz Vito (V447)",
  "Benefactor-Maybach Pullman",
  "Bestia GTS",
  "BF Injection",
  "Bison",
  "Blade",
  "Blista Kanjo",
  "Blista",
  "Bodhi",
  "Bravado Charger 1969",
  "Bravado Ram 1500",
  "Bravado Viper 2008",
  "Brawler",
  "Brioso R/A",
  "Buccaneer",
  "Buffalo",
  "Bullet",
  "Buzzard",
  "Calico GTF",
  "Caracara 4x4",
  "Carbonizzare",
  "Casco",
  "Cavalcade",
  "Cheburek",
  "Cheetah Classic",
  "Cheetah",
  "Chino",
  "Clique",
  "Cognoscenti 55",
  "Cognoscenti Cabrio",
  "Cognoscenti",
  "Coil Cybertruck",
  "Coil Model S",
  "Coil Model X",
  "Coil Roadster",
  "Comet S2",
  "Comet SR",
  "Comet",
  "Contender",
  "Coquette Blackfin",
  "Coquette D10",
  "Coquette",
  "Couquette Classic",
  "Cuban 800",
  "Cyclone",
  "Cypher",
  "Declasse Corvette C7",
  "Declasse Tahoe",
  "Deveste Eight",
  "Deviant",
  "Dilettante",
  "Dinghy (2-Seater)",
  "Dinghy (Yacht)",
  "Dinghy",
  "Dinka NSX 2017",
  "Dinka RT-3000",
  "Dodo",
  "Dominator ASP",
  "Dominator GTT",
  "Dominator GTX",
  "Dominator PiBwasser",
  "Dominator",
  "Drift Yosemite",
  "Dubsta 6x6",
  "Dubsta SG",
  "Dubsta",
  "Dukes",
  "Duster",
  "Elegy Retro Custom",
  "Elegy RH8",
  "Ellie",
  "Emperor LX-570",
  "Emperor RCF",
  "Emperor",
  "Entity XF",
  "Enus Continental GT",
  "Enus Cullinan",
  "Enus Phantom",
  "ETR-1",
  "Euros",
  "Exemplar",
  "F620",
  "Faction",
  "Felon GT",
  "Felon",
  "Feltzer",
  "Flash GT",
  "FMJ",
  "FQ 2",
  "Frogger",
  "Fugitive",
  "Furore GT",
  "Fusilade",
  "Futo GTX",
  "Futo",
  "Future Shock Issi",
  "Gallivanter Defender Christmas Edition",
  "Gallivanter Defender Halloween Edition",
  "Gauntlet Classic",
  "Gauntlet Hellfire",
  "Gauntlet Redwood",
  "Gauntlet",
  "GB200",
  "Glendale",
  "GP-1",
  "Granger",
  "Grotti Italia (F458)",
  "Growler",
  "GT 500",
  "Hermes",
  "Hotknife",
  "Howard NX-25",
  "Huntley S",
  "Imorgon",
  "Impaler",
  "Infernus Classic",
  "Infernus",
  "Ingot",
  "Issi",
  "Itali GTB Custom",
  "Itali GTB",
  "Itali GTO",
  "Jackal",
  "JB 700",
  "Jester (Racecar)",
  "Jester Classic",
  "Jester RR",
  "Jester",
  "Jetmax",
  "Journey",
  "Jugular",
  "Kamacho",
  "Karin Land Cruiser 200",
  "Karin Tundra 2021",
  "Khamelion",
  "Komoda",
  "Krieger",
  "Lampadati Giulia GTA",
  "Landstalker",
  "Luxor Deluxe",
  "Luxor",
  "Lynx",
  "Malard",
  "Mamba",
  "Mammatus",
  "Marquis",
  "Massacro",
  "Maverick",
  "Microlight",
  "Monroe",
  "Moonbeam",
  "Nebula Turbo",
  "Neon",
  "Nero Custom",
  "Nero",
  "Nightshade",
  "Nimbus",
  "Novak",
  "Obey A8",
  "Obey R8",
  "Obey RS6",
  "Obey RS7",
  "Ocelot F-Type R",
  "Ocelot Victor",
  "Oracle",
  "Osiris",
  "P-45 Nokota",
  "Panto",
  "Paragon R",
  "Pariah",
  "Patriot Stretch",
  "Patriot",
  "Pegassi Huayra BC",
  "Pegassi Performante (LP640)",
  "Penetrator",
  "Penumbra",
  "Peyote Gasser",
  "Pfister 811",
  "Pfister 918 Spyder",
  "Pfister Panamera",
  "Pfister Taycan",
  "Pheonix",
  "Picador",
  "Prairie",
  "Premier",
  "Previon",
  "Progen 675 LT",
  "Raiden",
  "Rancher XL",
  "Rapid GT",
  "Raptor",
  "Rat-Loader",
  "Rat-Truck",
  "RE-7B",
  "Reaper",
  "Rebel",
  "Rebla GTS",
  "Regina",
  "Remus",
  "Revolter",
  "Rhapsody",
  "Riata",
  "Rocoto",
  "Ruiner",
  "Rumpo",
  "Ruston",
  "Rusty Rebel",
  "Sabre Turbo",
  "Sandking SWB",
  "Sandking XL",
  "SC-1",
  "Schafter LWB (Armored)",
  "Schafter LWB",
  "Schafter V12",
  "Schafter",
  "Schlagen GT",
  "Schwarzer",
  "SeaShark",
  "Seminole",
  "Sentinel Classic",
  "Sentinel XS",
  "Serrano",
  "Seven-70",
  "Shelby GT500",
  "Slam Van",
  "Slamvan Custom",
  "Sparrow",
  "Specter",
  "Speeder",
  "Squalo",
  "Stafford",
  "Stallion",
  "Stinger GT",
  "Stinger",
  "Stirling GT",
  "Streiter",
  "Stretch",
  "Sultan Classic",
  "Sultan RS Classic",
  "Sultan RS",
  "Sultan",
  "Suntrap",
  "Super Diamond",
  "SuperVolito Carbon",
  "Surano",
  "Surge",
  "Swift Deluxe",
  "Swinger",
  "T-20",
  "Tailgater S",
  "Tailgater",
  "Taipan",
  "Tampa",
  "Tempesta",
  "Tezeract",
  "Thrax",
  "Tigon",
  "Torero",
  "Toro",
  "Toros",
  "Tropic",
  "Tropos Rallye",
  "Truffade Chiron",
  "Tulip",
  "Turismo Classic",
  "Turismo R",
  "Tyrant",
  "Tyrus",
  "Ubermacht 760 (LI)",
  "Ubermacht I8",
  "Ubermacht M3 (E46)",
  "Ubermacht M3 (G80)",
  "Ubermacht M5 (E34)",
  "Ubermacht M5 (E60)",
  "Ubermacht M8 (F91)",
  "Ubermacht X5 (E70)",
  "Ubermacht X5 (G05)",
  "Ubermacht X6-M (E71)",
  "Ubermacht X7 (G07)",
  "V-65 Molotok",
  "Vacca",
  "Vagner",
  "Vamos",
  "Vectre",
  "Velierer",
  "Velum",
  "Vigero",
  "Virgo Classic",
  "Virgo",
  "Viseris",
  "Visione",
  "Volatus",
  "Voltic",
  "Voodoo Custom",
  "Voodoo",
  "V-STR",
  "Warrener HKR",
  "Warrener",
  "Washington",
  "Windsor Drop",
  "Windsor",
  "X80 Proto",
  "XA-21",
  "XLS (Armored)",
  "XLS",
  "Yosemite Rancher",
  "Yosemite",
  "Zentorno",
  "Zion Cabrio",
  "Zion Classic",
  "Zion",
  "Zorrusso",
  "Z-Type",
  "Akuma",
  "Apocalypse Deathbike",
  "Avarus",
  "Bagger",
  "Bati 801",
  "Bati 801RR",
  "BF-400",
  "Blazer",
  "Blazer Lifeguard",
  "BMX",
  "Carbon RS",
  "Chimera",
  "Cliffhanger",
  "Cruiser",
  "Daemon",
  "Defiler",
  "Diabolus",
  "Diabolus Custom",
  "Double-T",
  "Enduro",
  "Esskey",
  "Faggio",
  "FCR 1000",
  "FCR 1000 Custom",
  "Future Shock Deathbike",
  "Gargoyle",
  "Hakuchou",
  "Hakuchou Drag",
  "Hexer",
  "Innovation",
  "Lectro",
  "Manchez",
  "Nemesis",
  "Nightblade",
  "PCJ-600",
  "Rat Bike",
  "Ruffian",
  "Sanchez",
  "Sanctus",
  "Shotaro",
  "Sovereign",
  "Street Blazer",
  "Stryder",
  "Thrust",
  "Tri-Cycles Race Bike",
  "Vader",
  "Vindicator",
  "Vortex",
  "Whippet Race Bike",
  "Wolfsbane",
  "Zombie Chopper",
];
